# Generated by Django 5.2 on 2025-05-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0004_post_image_alter_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statystyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=200)),
                ('wartosc', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('utworzono', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
