# Generated by Django 5.2 on 2025-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0005_statystyka'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZawodnikStatystyka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie_nazwisko', models.CharField(max_length=100)),
                ('numer', models.PositiveIntegerField()),
                ('wystepy', models.PositiveIntegerField(default=0)),
                ('gole', models.PositiveIntegerField(default=0)),
                ('asysty', models.PositiveIntegerField(default=0)),
                ('zolt_kartki', models.PositiveIntegerField(default=0)),
                ('czer_kartki', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
