# Generated by Django 5.2 on 2025-05-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pila', '0006_zawodnikstatystyka'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statystyka',
        ),
        migrations.AlterField(
            model_name='zawodnikstatystyka',
            name='asysty',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zawodnikstatystyka',
            name='czer_kartki',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zawodnikstatystyka',
            name='gole',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zawodnikstatystyka',
            name='wystepy',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='zawodnikstatystyka',
            name='zolt_kartki',
            field=models.PositiveIntegerField(),
        ),
    ]
