# Generated by Django 5.2.2 on 2025-06-05 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pila", "0007_delete_statystyka_alter_zawodnikstatystyka_asysty_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "opponent_name",
                    models.CharField(max_length=100, verbose_name="Przeciwnik"),
                ),
                ("match_date", models.DateTimeField(verbose_name="Data meczu")),
                (
                    "location",
                    models.CharField(
                        default="Stadion NRG", max_length=100, verbose_name="Miejsce"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mecz",
                "verbose_name_plural": "Mecze",
                "ordering": ["match_date"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data zakupu"),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="pila.match",
                        verbose_name="Mecz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bilet",
                "verbose_name_plural": "Bilety",
                "unique_together": {("user", "match")},
            },
        ),
    ]
