# Generated by Django 5.2.2 on 2025-06-05 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pila", "0008_match_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Ilość"),
        ),
    ]
