# Generated by Django 5.2.2 on 2025-06-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pila", "0009_ticket_quantity"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="match",
            name="base_ticket_price",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                max_digits=6,
                verbose_name="Cena bazowa biletu",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="price_paid_per_ticket",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=6,
                verbose_name="Zapłacona cena za bilet",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ticket",
            name="total_price_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Całkowita zapłacona cena",
            ),
            preserve_default=False,
        ),
    ]
