# Generated by Django 5.2.2 on 2025-06-06 14:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pila", "0010_alter_ticket_unique_together_match_base_ticket_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Nazwa typu biletu"
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="Zniżka (%)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Typ biletu",
                "verbose_name_plural": "Typy biletów",
            },
        ),
        migrations.AlterField(
            model_name="match",
            name="base_ticket_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("50.00"),
                max_digits=6,
                verbose_name="Cena bazowa biletu (normalny)",
            ),
        ),
    ]
