# Generated by Django 5.2.2 on 2025-06-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pila", "0011_tickettype_alter_match_base_ticket_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="pila.tickettype",
                verbose_name="Typ biletu",
            ),
            preserve_default=False,
        ),
    ]
